"""
Plaintext MobileGestalt property names, for turning the obfuscated keys TikTok
asks for back into something readable.

Apple does not pass the property name to MGCopyAnswer. It passes

    base64(md5("MGCopyAnswer" + name))[:22]

a one-way 22-character token. There is no decoding it, only matching a known name
against it, which works because MD5 is fast and the space of real Apple property
names is small.

This file stores the NAMES, never the hashes, and derives the lookup at import.
That makes it self-verifying: a typo produces a hash that never matches anything,
rather than a wrong label sitting on a real key. Adding a newly discovered
property is a one-line edit here and nothing else.

Provenance: merged from PoomSmart/MGKeys (deobfuscated.py and
deobfuscated_legacy.py), every entry re-hashed here and confirmed to reproduce its
published token before being written. Those tables are themselves brute-force
recoveries covering roughly 85 percent of the keys inside libMobileGestalt.dylib,
so an unresolved hash means "not publicly recovered yet", not "not a real key".

A few entries are visibly mangled by the upstream extraction (names ending in a
stray quote and paren). Both the raw and the cleaned form are kept rather than
guessed between: an entry nothing ever asks for costs one dictionary slot and can
never produce a wrong answer.

To refresh:
    curl -sSLO https://raw.githubusercontent.com/PoomSmart/MGKeys/master/deobfuscated.py
"""
import base64
import hashlib

NAMES = [
    "3GProximityCapability", "3GVeniceCapability", "3Gvenice", "3d-imagery", "3d-maps",
    "64-bit", "720p", "720pPlaybackCapability", "ADSCapability", "APNCapability",
    "ARM64ExecutionCapability", "ARMV6ExecutionCapability", "ARMV7ExecutionCapability",
    "ARMV7SExecutionCapability", "ASTC", "AV1DecodingCapability", "AVDDecodingRate",
    "AWDID", "AWDLCapability", "AbsoluteDepthLimit", "AccelerometerCapability",
    "AccessibilityCapability", "AcousticID", "ActivationProtocol",
    "ActiveWirelessTechnology", "ActuatorResonantFrequency",
    "AdditionalTextTonesCapability", "AggregateDevicePhotoZoomFactor",
    "AggregateDeviceVideoZoomFactor", "AirDropCapability", "AirDropRestriction",
    "AirplaneMode", "AirplayMirroringCapability", "Allow32BitApps", "AllowOnlyATVCPSDKApps",
    "AllowPhoneApp", "AllowYouTube", "AllowYouTubePlugin", "AlwaysOnDisplayMaxMemory",
    "AmbientLightSensorCapability", "AmbientLightSensorSerialNumber", "ApNonce",
    "ApNonceRetrieve", "AppCapacityTVOS", "AppStore", "AppStoreCapability",
    "AppleInternalInstallCapability", "AppleNeuralEngineSubtype", "AppleSPUHIDDriver",
    "ApplicationInstallationCapability", "ArcModuleSerialNumber", "ArrowChipID",
    "ArrowUniqueChipID", "ArtworkTraitDisplayGamut", "ArtworkTraits", "AssistantCapability",
    "AttestationUniqueDeviceID", "AudioExclaveMicInputCapability",
    "AudioPlaybackCapability", "AutoFocusCameraCapability", "AutomaticMicMode",
    "AvailableDisplayZoomSizes", "BacklightCapability", "BasebandAPTimeSync",
    "BasebandBoardSnum", "BasebandCertId", "BasebandChipId", "BasebandChipset",
    "BasebandClass", "BasebandFirmwareManifestData", "BasebandFirmwareUpdateInfo",
    "BasebandFirmwareVersion", "BasebandKeyHashInformation", "BasebandPostponementStatus",
    "BasebandPostponementStatusBlob", "BasebandRegionSKU",
    "BasebandRegionSKURadioTechnology", "BasebandSecurityInfoBlob", "BasebandSerialNumber",
    "BasebandStatus", "BasebandUniqueId", "BatteryCurrentCapacity", "BatteryIsCharging",
    "BatteryIsFullyCharged", "BatterySerialNumber", "BlueLightReductionSupported",
    "BluetoothAddress", "BluetoothAddressData", "BluetoothCapability",
    "BluetoothLE2Capability", "BluetoothLECapability", "BoardId", "BoardRevision",
    "BootManifestHash", "BootNonce", "BridgeBuild", "BridgeRestoreVersion",
    "BuddyLanguagesAnimationRequiresOptimization", "BuildID", "BuildVersion",
    "C2KDeviceCapability", "CPUArchitecture", "CPUSubType", "CPUType",
    "CallForwardingCapability", "CallWaitingCapability", "CallerIDCapability",
    "CameraAppUIVersion", "CameraButtonCGRect", "CameraButtonCapability",
    "CameraButtonNormalizedCGRect", "CameraCapability", "CameraFlashCapability",
    "CameraFrontFlashCapability", "CameraHDR2Capability", "CameraHDRVersion",
    "CameraIMUDistanceType", "CameraLiveEffectsCapability", "CameraMaxBurstLength",
    "CameraRestriction", "CarrierBundleInfoArray", "CarrierInstallCapability",
    "CellBroadcastCapability", "CellularDataCapability", "CellularTelephonyCapability",
    "CertificateProductionStatus", "CertificateSecurityMode", "ChipConfigRack", "ChipID",
    "ChromeIdentifier", "CloudPhotoLibraryCapability", "CoastlineGlowRenderingCapability",
    "CompassCalibration", "CompassCalibrationDictionary", "CompassType",
    "CompatibleAppVariants", "ComputerName", "ConferenceCallType", "ConfigNumber",
    "ContainsCellularRadioCapability", "ContinuityCapability", "CoreRoutineCapability",
    "CountryOfOrigin", "CoverglassSerialNumber", "DMin", "DataCenterRegionCode",
    "DataPlanCapability", "DebugBoardRevision", "DelaySleepForHeadsetClickCapability",
    "DesenseBuild", "DeviceAlwaysPrewarmActuator", "DeviceBackGlassMaterial",
    "DeviceBackingColor", "DeviceBrand", "DeviceClass", "DeviceClassNumber", "DeviceColor",
    "DeviceColorMapPolicy", "DeviceCoprocessorIsT1", "DeviceCornerRadius",
    "DeviceCoverGlassCoating", "DeviceCoverGlassColor", "DeviceCoverGlassMaterial",
    "DeviceCoverMaterial", "DeviceDBVDependentVSHCompensationTraits",
    "DeviceDefaultsToAnalyticsOptIn", "DeviceDisablesAODByDefault", "DeviceEnclosureColor",
    "DeviceEnclosureMaterial", "DeviceEnclosureRGBColor", "DeviceHasAggregateCamera",
    "DeviceHasEmbeddedSIMOnlyBoard", "DeviceHasNAN", "DeviceHousingColor",
    "DeviceHousingColorUncooked", "DeviceIsMuseCapable", "DeviceIsNED",
    "DeviceIsPortableMac", "DeviceKeyboardCalibration", "DeviceLaunchTimeLimitScale",
    "DeviceLowBatteryLevel", "DeviceMemorySize", "DeviceMesaType", "DeviceName",
    "DeviceNameString", "DevicePrefers3DBuildingStrokes", "DevicePrefersBuildingStrokes",
    "DevicePrefersCheapTrafficShaders", "DevicePrefersProceduralAntiAliasing",
    "DevicePrefersTrafficAlpha", "DeviceProximityCapability", "DeviceRGBColor",
    "DeviceRequiresPetalOptimization", "DeviceRequiresProximityAmeliorations",
    "DeviceRequiresSoftwareBrightnessCalculations", "DeviceSceneUpdateTimeLimitScale",
    "DeviceStingHousingColor", "DeviceSubBrand", "DeviceSuportsExternalDriverKit",
    "DeviceSupports1080p", "DeviceSupports3DImagery", "DeviceSupports3DMaps",
    "DeviceSupports3rdPartyHaptics", "DeviceSupports4G", "DeviceSupports4k",
    "DeviceSupports64Bit", "DeviceSupports720p", "DeviceSupports80ChargeLimit",
    "DeviceSupports9Pin", "DeviceSupportsAODVibrancy", "DeviceSupportsAOP",
    "DeviceSupportsAOP2", "DeviceSupportsARKit", "DeviceSupportsASTC",
    "DeviceSupportsAbsoluteAltimeter", "DeviceSupportsAbsoluteDepth",
    "DeviceSupportsActionAfterPowerConnect", "DeviceSupportsActiveNFCReadingOnly",
    "DeviceSupportsAdaptiveMapsUI", "DeviceSupportsAdvancedMapRendering",
    "DeviceSupportsAdvancedVoiceProcessorChatFlavor", "DeviceSupportsAlmond",
    "DeviceSupportsAlwaysAPVoiceTrigger", "DeviceSupportsAlwaysListening",
    "DeviceSupportsAlwaysOnCompass", "DeviceSupportsAlwaysOnDisplay",
    "DeviceSupportsAlwaysOnDisplayFlipbook", "DeviceSupportsAlwaysOnTime",
    "DeviceSupportsAppleLPM", "DeviceSupportsApplePencil", "DeviceSupportsAudioMix",
    "DeviceSupportsAutoDim", "DeviceSupportsAutoLowLightVideo", "DeviceSupportsAvatars",
    "DeviceSupportsBatteryInformation", "DeviceSupportsBatteryModuleAuthentication",
    "DeviceSupportsBeacon", "DeviceSupportsBerkelium2", "DeviceSupportsBootChime",
    "DeviceSupportsBreathingDisturbancesMeasurements", "DeviceSupportsBrook",
    "DeviceSupportsCCK", "DeviceSupportsCameraCaptureOnTouchDown",
    "DeviceSupportsCameraDeferredProcessing", "DeviceSupportsCameraHaptics",
    "DeviceSupportsCarIntegration", "DeviceSupportsCarPlay2", "DeviceSupportsCinnamon",
    "DeviceSupportsClosedLoopHaptics", "DeviceSupportsCollisionSOS",
    "DeviceSupportsCompassOrienteering", "DeviceSupportsConcurrentHPLPMics",
    "DeviceSupportsContextualVolume", "DeviceSupportsCorrectedTemperature",
    "DeviceSupportsCrudeProx", "DeviceSupportsCyclingAutoStartReminders",
    "DeviceSupportsDCP", "DeviceSupportsDClr", "DeviceSupportsDarwinInitConfigFromNVRAM",
    "DeviceSupportsDisplayPort", "DeviceSupportsDoNotDisturbWhileDriving",
    "DeviceSupportsDynamicEndOfCharge", "DeviceSupportsDynamicEndOfChargeLegacyHW",
    "DeviceSupportsDynamicIsland", "DeviceSupportsELabel", "DeviceSupportsEUCapabilities",
    "DeviceSupportsElton", "DeviceSupportsEnhancedAC3",
    "DeviceSupportsEnhancedMultitasking", "DeviceSupportsEnvironmentalDosimetry",
    "DeviceSupportsExternalHDR", "DeviceSupportsFairPlaySecureVideoPath",
    "DeviceSupportsFindApplePencil", "DeviceSupportsFloorCounting",
    "DeviceSupportsFrameSynchronousBrightness", "DeviceSupportsGammaContrastPreservation",
    "DeviceSupportsGenerativeModelSystems", "DeviceSupportsGrayDimming",
    "DeviceSupportsGrey", "DeviceSupportsHDRDeferredProcessing",
    "DeviceSupportsHDRPhotoDisplay", "DeviceSupportsHMEInARKit",
    "DeviceSupportsHandwritingSynthesisModel", "DeviceSupportsHaptics",
    "DeviceSupportsHardwareDetents", "DeviceSupportsHeartHealthAlerts",
    "DeviceSupportsHeartRateVariability", "DeviceSupportsHiResBuildings",
    "DeviceSupportsHypertensivePatternMeasurements",
    "DeviceSupportsIndependentOutputOnSpeaker", "DeviceSupportsInductiveCharging",
    "DeviceSupportsLaguna", "DeviceSupportsLandscapeFaceID",
    "DeviceSupportsLanguageDownloadUI", "DeviceSupportsLineIn",
    "DeviceSupportsLiquidDetection_CorrosionMitigation", "DeviceSupportsLiveActivities",
    "DeviceSupportsLivePhotoAuto", "DeviceSupportsLiveVideoRendering",
    "DeviceSupportsLockdown", "DeviceSupportsLongFormAudio", "DeviceSupportsLowLatency",
    "DeviceSupportsLowPowerSoundClassification", "DeviceSupportsMTP",
    "DeviceSupportsMapsBlurredUI", "DeviceSupportsMapsOpticalHeading",
    "DeviceSupportsMomentCapture", "DeviceSupportsMultiUser", "DeviceSupportsNFC",
    "DeviceSupportsNavigation", "DeviceSupportsNewton",
    "DeviceSupportsOnDemandPhotoAnalysis", "DeviceSupportsP3ColorspaceVideoRecording",
    "DeviceSupportsPeriodicALSUpdates", "DeviceSupportsPersonalTranslator",
    "DeviceSupportsPhotosInpainting", "DeviceSupportsPhotosLocalLight",
    "DeviceSupportsPortraitIntensityAdjustments",
    "DeviceSupportsPortraitLightEffectFilters", "DeviceSupportsPulseWidthMaximization",
    "DeviceSupportsRGB10", "DeviceSupportsRaiseToSpeak", "DeviceSupportsReverseZoom",
    "DeviceSupportsSWProRes", "DeviceSupportsScandium", "DeviceSupportsSecureDoubleClick",
    "DeviceSupportsSecureMicrophone", "DeviceSupportsSiDP",
    "DeviceSupportsSideButtonClickSpeed", "DeviceSupportsSimplisticRoadMesh",
    "DeviceSupportsSingleCameraPortrait", "DeviceSupportsSingleDisplayEnhancedMultitasking",
    "DeviceSupportsSiriBargeIn", "DeviceSupportsSiriHub", "DeviceSupportsSiriSpeaks",
    "DeviceSupportsSiriSpokenMessages", "DeviceSupportsSiriUnderstandingOnDevice",
    "DeviceSupportsSpatialAudioCapture", "DeviceSupportsSpatialFaceTimeAudioPlayback",
    "DeviceSupportsSpatialOverCapture", "DeviceSupportsStageLightPortraitPreview",
    "DeviceSupportsStereoAudioRecording", "DeviceSupportsStudioLightPortraitPreview",
    "DeviceSupportsSwimmingWorkouts", "DeviceSupportsTapToWake",
    "DeviceSupportsTelephonyOverUSB", "DeviceSupportsTethering",
    "DeviceSupportsThunderbolt", "DeviceSupportsTimeInDaylight",
    "DeviceSupportsToneMapping", "DeviceSupportsTwilight", "DeviceSupportsUSBTypeC",
    "DeviceSupportsUSBTypeCDisplay", "DeviceSupportsUSLegallyCompliantBloodOxygen",
    "DeviceSupportsUltraLowPowerNetworking", "DeviceSupportsUnconditionalPluckItCollection",
    "DeviceSupportsUntrustedRemoteSysdiagnose", "DeviceSupportsVSHCompensation",
    "DeviceSupportsVirtualResearchEnvironment", "DeviceSupportsVoiceOverCanUseSiriVoice",
    "DeviceSupportsWalkingRadiusAnimation", "DeviceSupportsWatchSpeakerPlayback",
    "DeviceSupportsWebkit", "DeviceSupportsWirelessChargingEnergyUseNotification",
    "DeviceSupportsWirelessSplitting", "DeviceSupportsYCbCr10", "DeviceSupportseARC",
    "DeviceVariant", "DeviceVariantGuess", "DiagData", "DictationCapability", "DieId",
    "DiskUsage", "DisplayBootRotation", "DisplayDriverICChipID",
    "DisplayFCCLogosViaSoftwareCapability", "DisplayInactiveBrightnessClass",
    "DisplayMaxNits", "DisplayMirroringCapability", "DisplayPortCapability",
    "DualSIMActivationPolicyCapable", "DynamicFunctionRowSerialNumber",
    "EOSHalleyConfiguration", "EUICCChipID", "EffectiveProductionStatus",
    "EffectiveProductionStatusAp", "EffectiveProductionStatusSEP", "EffectiveSecurityMode",
    "EffectiveSecurityModeAp", "EffectiveSecurityModeSEP", "EncodeAACCapability",
    "EncryptedDataPartitionCapability", "EnforceCameraShutterClick", "EnforceGoogleMail",
    "EphemeralDataModeEnabled", "EphemeralDataModeOverride", "EthernetMacAddress",
    "EthernetMacAddressData", "ExclaveCapability", "ExplicitContentRestriction",
    "ExtendedLOMMacAddress", "ExtendedLOMMacAddressData", "ExtendedSecurityDomain",
    "ExternalChargeCapability", "ExternalPowerSourceConnected", "FDRSealingStatus",
    "FMFAllowed", "FaceTimeBackCameraTemporalNoiseReductionMode", "FaceTimeBitRate2G",
    "FaceTimeBitRate3G", "FaceTimeBitRateLTE", "FaceTimeBitRateWiFi",
    "FaceTimeCameraRequiresFastSwitchOptions",
    "FaceTimeCameraSupportsHardwareFaceDetection", "FaceTimeDecodings", "FaceTimeEncodings",
    "FaceTimeFrontCameraTemporalNoiseReductionMode", "FaceTimePhotosOptIn",
    "FaceTimePreferredDecoding", "FaceTimePreferredEncoding", "FanCount", "FirmwareNonce",
    "FirmwarePreflightInfo", "FirmwareVersion", "FirstPartyLaunchTimeLimitScale",
    "ForwardCameraCapability", "FramebufferIdentifier",
    "FrontCameraOffsetFromDisplayCenter", "FrontCameraRotationForISP",
    "FrontCameraRotationFromDisplayNormal", "FrontFacingCameraAutoHDRCapability",
    "FrontFacingCameraBurstCapability", "FrontFacingCameraCapability",
    "FrontFacingCameraHDRCapability", "FrontFacingCameraHDROnCapability",
    "FrontFacingCameraHFRCapability", "FrontFacingCameraHFRVideoCapture1080pMaxFPS",
    "FrontFacingCameraHFRVideoCapture720pMaxFPS", "FrontFacingCameraMaxVideoZoomFactor",
    "FrontFacingCameraModuleSerialNumber", "FrontFacingCameraSingleCameraPortrait",
    "FrontFacingCameraStageLightPortraitCaptureCapability",
    "FrontFacingCameraStillDurationForBurst", "FrontFacingCameraSuperWideCameraCapability",
    "FrontFacingCameraVariableFrameRateCapability",
    "FrontFacingCameraVideoCapture1080pMaxFPS", "FrontFacingCameraVideoCapture4kMaxFPS",
    "FrontFacingCameraVideoCapture720pMaxFPS", "FrontFacingIRCameraModuleSerialNumber",
    "FrontFacingIRStructuredLightProjectorModuleSerialNumber",
    "FrontFacingLowLightCameraCapability", "Full6FeaturesCapability", "GPSCapability",
    "GSDeviceName", "GameKitCapability", "GasGaugeBatteryCapability",
    "GreenTeaDeviceCapability", "GroundhogEnabled", "GyroscopeCapability",
    "H264EncoderCapability", "HDRImageCaptureCapability", "HDVideoCaptureCapability",
    "HEVCDecoder10bitSupported", "HEVCDecoder12bitSupported", "HEVCDecoder8bitSupported",
    "HEVCEncodingCapability", "HMERefreshRateInARKit", "HWModelDescriptionForAnalytics",
    "HWModelDescriptionForAudio", "HWModelDescriptionForAutomatedTesting",
    "HWModelDescriptionForCamera", "HWModelDescriptionForPowerPerf",
    "HWModelDescriptionForUserVisibility", "HWModelStr", "HWModelUniqueStr",
    "HallEffectSensorCapability", "HapticsPowerControlFeatures",
    "HardwareEncodeSnapshotsCapability", "HardwareKeyboardCapability", "HardwarePlatform",
    "HardwareSnapshotsRequirePurpleGfxCapability", "HardwareSupportsSecureDoubleClick",
    "HasAllFeaturesCapability", "HasAppleNeuralEngine", "HasBaseband", "HasBattery",
    "HasDaliMode", "HasExtendedColorDisplay", "HasHighBandwidthRadio", "HasIcefall",
    "HasInternalSettingsBundle", "HasMesa", "HasPKA", "HasPartiallyOccludedDisplay",
    "HasSEP", "HasSpringBoard", "HasThinBezel", "HealthKitCapability",
    "HearingAidAudioEqualizationCapability", "HearingAidLowEnergyAudioCapability",
    "HearingAidPowerReductionCapability", "HiDPICapability", "HiccoughInterval",
    "HideNonDefaultApplicationsCapability", "HighestSupportedVideoMode", "HomeButtonType",
    "HomeScreenWallpaperCapability", "HorsemanCapability",
    "HumanReadableProductVersionString", "IDAMCapability",
    "IOSurfaceBackedImagesCapability", "IOSurfaceFormatDictionary", "IceFallID",
    "IcefallInRestrictedMode", "IcefallInfo", "Image4CryptoHashMethod", "Image4Supported",
    "InDiagnosticsMode", "IntegratedCircuitCardIdentifier",
    "IntegratedCircuitCardIdentifier2", "InternalBuild",
    "InternationalMobileEquipmentIdentity", "InternationalMobileEquipmentIdentity2",
    "InternationalSettingsCapability", "InverseDeviceID", "IsComputeController",
    "IsComputeNode", "IsComputePacketBridge", "IsEmulatedDevice", "IsFactorySignedRestore",
    "IsLargeFormatPhone", "IsPwrOpposedVol", "IsServicePart", "IsSimulatedDevice",
    "IsSimulator", "IsSolariumLowPerformanceDevice",
    "IsThereEnoughBatteryLevelForSoftwareUpdate", "IsUIBuild", "IsVirtualDevice",
    "JasperSerialNumber", "KeyboardMutePreservesRegionalShutterClickBehavior",
    "KeyboardMutePreservesRegionalShutterClickBehaviorForLegacyDevices",
    "LTEDeviceCapability", "LaunchTimeLimitScaleSupported", "LiDARCalibrationPrCL",
    "LisaCapability", "LoadThumbnailsWhileScrollingCapability", "LocalizedDeviceNameString",
    "LocationRemindersCapability", "LocationServicesCapability",
    "LowPowerExpressModesSupported", "LowPowerWalletMode", "LunaFlexSerialNumber",
    "LynxPublicKey", "LynxSerialNumber", "MLBSerialNumber", "MLEHW", "MMSCapability",
    "MacBridgingKeys", "MacFormFactor", "MacPrefsAssetImage", "MagnetometerCapability",
    "MainDisplayRotation", "MainScreenCanvasSizes", "MainScreenClass", "MainScreenHeight",
    "MainScreenOrientation", "MainScreenPitch", "MainScreenScale", "MainScreenStaticInfo",
    "MainScreenWidth", "MarketingDeviceFamilyName", "MarketingNameString",
    "MarketingProductName", "MarketingSOCNameString", "MarketingVersion",
    "MaxH264PlaybackLevel", "MaximumScreenScale", "MedusaFloatingLiveAppCapability",
    "MedusaOverlayAppCapability", "MedusaPIPCapability", "MedusaPinnedAppCapability",
    "MesaSerialNumber", "MetalCapability", "MetalPerfLevelCapability",
    "MicrophoneCapability", "MicrophoneCount", "MinimumSupportediTunesVersion",
    "MixAndMatchPrevention", "MobileDeviceMinimumVersion", "MobileEquipmentIdentifier",
    "MobileEquipmentInfoBaseId", "MobileEquipmentInfoBaseProfile",
    "MobileEquipmentInfoBaseVersion", "MobileEquipmentInfoCSN",
    "MobileEquipmentInfoDisplayCSN", "MobileSubscriberCountryCode",
    "MobileSubscriberNetworkCode", "MobileWifi", "ModelNumber", "MonarchLowEndHardware",
    "MultiLynxPublicKeyArray", "MultiLynxSerialNumberArray", "MultiTouchCapability",
    "MultiTouchMaxBootTime", "MultitaskingCapability", "MultitaskingGesturesCapability",
    "MusicStore", "MusicStoreCapability", "N78aHack", "NFCRadio",
    "NFCRadioCalibrationDataPresent", "NFCUniqueChipID", "NVRAMDictionary",
    "NandControllerUID", "NavajoFusingState", "NikeIpodCapability",
    "NotGreenTeaDeviceCapability", "NumOfFans", "NumOfUSBPorts", "OLEDDisplay",
    "OSMigrationCapability", "OTAActivationCapability", "OceanComputeCarrierID",
    "OceanComputeCarrierSlot", "OfflineDictationCapability", "OnDeviceSiriCapability",
    "OpenGLES1Capability", "OpenGLES2Capability", "OpenGLES3Capability", "OpenGLESVersion",
    "OysterCapability", "PTPLargeFilesCapability", "PanelSerialNumber",
    "PanoramaCameraCapability", "PartitionStyle", "PartitionType", "PasswordConfigured",
    "PasswordProtected", "PearlCameraCapability", "PearlIDCapability",
    "PearlMotionDetectionCapability", "PeekUICapability", "PeekUIWidth",
    "Peer2PeerCapability", "PerfLevelCapability", "PersonalHotspotCapability",
    "PhoneNumber", "PhoneNumber2", "PhosphorusCapability", "PhotoAdjustmentsCapability",
    "PhotoCapability", "PhotoSharingCapability", "PhotoStreamCapability",
    "PhotosPostEffectsCapability", "PhysicalHardwareNameString", "PiezoClickerCapability",
    "PintoMacAddress", "PintoMacAddressData", "PipelinedStillImageProcessingCapability",
    "PlatformStandAloneContactsCapability", "PlatinumCapability", "PressDemoMode",
    "ProductHash", "ProductName", "ProductType", "ProductTypeDescForAnalytics",
    "ProductTypeDescForAudio", "ProductTypeDescForAutomatedTesting",
    "ProductTypeDescForCamera", "ProductTypeDescForPowerPerf",
    "ProductTypeDescForUserVisibility", "ProductVersion", "ProductVersionExtra",
    "ProvisioningUniqueDeviceID", "ProximitySensorCalibration",
    "ProximitySensorCalibrationDictionary", "ProximitySensorCapability",
    "QuickNoteCapability", "RF-exposure-separation-distance",
    "RFExposureSeparationDistance", "RawPanelSerialNumber", "RearALSCapability",
    "RearCameraCapability", "RearCameraOffsetFromDisplayCenter",
    "RearFacingCamera60fpsVideoCaptureCapability", "RearFacingCameraAutoHDRCapability",
    "RearFacingCameraBurstCapability", "RearFacingCameraCapability",
    "RearFacingCameraFocusPixelCalibrationCapability", "RearFacingCameraHDRCapability",
    "RearFacingCameraHDROnCapability", "RearFacingCameraHFRCapability",
    "RearFacingCameraHFRVideoCapture1080pMaxFPS",
    "RearFacingCameraHFRVideoCapture720pMaxFPS", "RearFacingCameraMaxVideoZoomFactor",
    "RearFacingCameraModuleSerialNumber",
    "RearFacingCameraStageLightPortraitCaptureCapability",
    "RearFacingCameraStillDurationForBurst", "RearFacingCameraSuperWideCameraCapability",
    "RearFacingCameraTimeOfFlightCameraCapability",
    "RearFacingCameraVariableFrameRateCapability",
    "RearFacingCameraVideoCapture1080pMaxFPS", "RearFacingCameraVideoCapture4kMaxFPS",
    "RearFacingCameraVideoCapture720pMaxFPS", "RearFacingCameraVideoCaptureFPS",
    "RearFacingLowLightCameraCapability", "RearFacingSuperWideCameraModuleSerialNumber",
    "RearFacingTelephotoCameraCapability", "RearFacingTelephotoCameraModuleSerialNumber",
    "ReceiveARCStreamOverAirPlayCapability", "RecoveryOSVersion", "RegionCode",
    "RegionInfo", "RegionInfoFromActivation", "RegionInfoFromSysconfig",
    "RegionSupportsCinnamon", "RegionalBehaviorAll", "RegionalBehaviorChinaBrick",
    "RegionalBehaviorEUVolumeLimit", "RegionalBehaviorGB18030",
    "RegionalBehaviorGoogleMail", "RegionalBehaviorNTSC",
    "RegionalBehaviorNoPasscodeLocationTiles", "RegionalBehaviorNoVOIP",
    "RegionalBehaviorNoWiFi", "RegionalBehaviorShutterClick", "RegionalBehaviorValid",
    "RegionalBehaviorVolumeLimit", "RegionalBehaviorsFromActivation",
    "RegulatoryModelNumber", "ReleaseType", "RemoteBluetoothAddress",
    "RemoteBluetoothAddressData", "RenderWideGamutImagesAtDisplayTime",
    "RendersLetterPressSlowly", "RequiredBatteryLevelForSoftwareUpdate",
    "RequiresNaturalVolumeButtonArrangement", "RequiresPairedRemote", "ResearchFuse",
    "RestoreOSBuild", "RestrictedCountryCodes", "RingerButtonCGRect",
    "RingerButtonCapability", "RingerButtonNormalizedCGRect", "RingerSwitchCapability",
    "RosalineSerialNumber", "RoswellChipID", "RotateToWakeStatus", "RunnableArchitectures",
    "SBAllowSensitiveUI", "SBCanForceDebuggingInfo", "SDIOManufacturerTuple",
    "SDIOProductInfo", "SEInfo", "SEPNonce", "SIMCapability", "SIMPhonebookCapability",
    "SIMStatus", "SIMStatus2", "SIMTrayStatus", "SIMTrayStatus2", "SMSCapability",
    "SavageChipID", "SavageInfo", "SavageSerialNumber", "SavageUID", "ScreenCaptureHeight",
    "ScreenCaptureWidth", "ScreenDimensionsCapability", "ScreenRecorderCapability",
    "ScreenSerialNumber", "SecondaryBluetoothMacAddress",
    "SecondaryBluetoothMacAddressData", "SecondaryEthernetMacAddress",
    "SecondaryEthernetMacAddressData", "SecondaryWifiMacAddress",
    "SecondaryWifiMacAddressData", "SecureElement", "SecureElementID", "SecurityDomain",
    "SensitiveUICapability", "SerialNumber", "ShoeboxCapability", "ShouldHactivate",
    "SiKACapability", "SigningFuse", "SiliconBringupBoard",
    "SimultaneousCallAndDataCurrentlySupported", "SimultaneousCallAndDataSupported",
    "SiriGestureCapability", "SiriOfflineCapability", "Skey", "SoCSKU", "SoftwareBehavior",
    "SoftwareBundleVersion", "SoftwareDimmingAlpha", "SpatialAudioProfileCapability",
    "SpeakerCalibrationMiGa", "SpeakerCalibrationSpGa", "SpeakerCalibrationSpTS",
    "SphereCapability", "StarkCapability", "StockholmJcopInfo", "StoreDemoMode",
    "StrictWakeKeyboardCases", "SubProductType", "SupplementalBuildVersion",
    "SupportedDeviceFamilies", "SupportedKeyboards", "SupportsBurninMitigation",
    "SupportsEDUMU", "SupportsForceTouch", "SupportsIrisCapture", "SupportsLEDAging",
    "SupportsLowPowerMode", "SupportsPerseus", "SupportsRotateToWake", "SupportsSOS",
    "SupportsSSHBButtonType", "SupportsTapToWake", "SupportsTouchRemote", "SysCfg",
    "SysCfgDict", "SystemImageID", "SystemTelephonyOfAnyKindCapability",
    "TVOutCrossfadeCapability", "TVOutSettingsCapability", "TargetSubType",
    "TelephonyCapability", "TelephonyMaximumGeneration", "ThinningProductType",
    "ThreadRadioCapability", "ThreadRadioMacAddress", "ThreadRadioMacAddress64Bit",
    "ThreadRadioMacAddress64BitData", "ThreadRadioMacAddressData",
    "ThreadRadioMacAddressForProvisioning", "ThreadRadioMacAddressForProvisioningData",
    "TimeSyncCapability", "TopModuleAuthChipID", "TorpedoCapability", "TouchDelivery120Hz",
    "TouchIDCapability", "TribecaSettings", "TristarID", "UIBackgroundQuality",
    "UIParallaxCapability", "UIProceduralWallpaperCapability", "UIReachability",
    "UMTSDeviceCapability", "USBPortCount", "UnifiedGamingPerfLevelMacTier1",
    "UnifiedGamingPerfLevelMacTier2", "UnifiedGamingPerfLeveliPadTier1",
    "UnifiedGamingPerfLeveliPadTier2", "UnifiedIPodCapability", "UniqueChipID",
    "UniqueChipIDString", "UniqueDeviceID", "UniqueDeviceIDData", "UserAssignedDeviceName",
    "UserIntentPhysicalButtonCGRect", "UserIntentPhysicalButtonCGRectString",
    "UserIntentPhysicalButtonNormalizedCGRect", "VMUniqueDeviceIDData", "VOIPCapability",
    "VSHCompensationMinimumNits", "VeniceCapability", "VibratorCapability",
    "VideoCameraCapability", "VideoStillsCapability", "VoiceControlCapability",
    "VolumeButtonCapability", "VolumeDownButtonCGRect", "VolumeDownButtonNormalizedCGRect",
    "VolumeUpButtonCGRect", "VolumeUpButtonNormalizedCGRect", "WAGraphicQuality",
    "WAPICapability", "WLANBkgScanCache", "WSKU", "WatchAppButtonCapability",
    "WatchCompanionCapability", "WatchKeyboardCapability",
    "WatchSupportsAutoPlaylistPlayback", "WatchSupportsHighQualityClockFaceGraphics",
    "WatchSupportsListeningOnGesture", "WatchSupportsMusicStreaming",
    "WatchSupportsSiriCommute", "WatchSupportsVoiceEditing", "WiFiCallingCapability",
    "WiFiCapability", "WiFiChipsetRevision", "WifiAddress", "WifiAddressData",
    "WifiAntennaSKUVersion", "WifiCallingSecondaryDeviceCapability", "WifiChipset",
    "WifiFirmwareVersion", "WifiVendor", "WirelessBoardSnum", "WirelessChargingCapability",
    "WorkoutUltraMode", "YonkersChipID", "YonkersSerialNumber", "YonkersUID",
    "YouTubeCapability", "YouTubePluginCapability", "absolute-depth",
    "absolute-depth-limit", "accel", "accelerometer", "accessibility", "acoustic-id",
    "adaptive-ui", "additional-text-tones", "aggregate-cam-photo-zoom",
    "aggregate-cam-video-zoom", "aggregate-camera", "airDropRestriction",
    "airplay-mirroring", "airplay-no-mirroring", "all-features", "allow-32bit-apps",
    "always-on-time", "ambient-light-sensor", "ambient-light-sensor-serial-num", "ane",
    "ane-type", "any-telephony", "aod-default-disable", "aod-max-mem", "aot-class", "apn",
    "apple-graphics-performance-tier", "apple-internal-install", "applicationInstallation",
    "arkit", "arm64", "arm64e", "armv6", "armv7", "armv7s", "assistant",
    "audio-earc-support", "auto-focus", "auto-focus-camera", "auto-low-light-video",
    "avatar-camera", "backlight", "baseband-chipset", "bitrate-2g", "bitrate-3g",
    "bitrate-lte", "bitrate-wifi", "bluetooth", "bluetooth-dev-addr0", "bluetooth-le",
    "bluetooth-lea2", "board-id", "board-revision", "boot-manifest-hash", "boot-nonce",
    "builtin-mics", "c2k-device", "calibration", "call-forwarding", "call-waiting",
    "caller-id", "camera-flash", "camera-front", "camera-front-flash", "camera-hdr-version",
    "camera-rear", "camera-ui-version", "cameraRestriction", "car-integration", "carplay-2",
    "cell-broadcast", "cellular-data", "certificate-production-status",
    "certificate-security-mode", "chip-config-rack", "chip-id", "chrome-identifier",
    "class", "closed-loop", "collision-sos", "config-number", "contains-cellular-radio",
    "continuity-camera", "country-of-origin", "coverglass-serial-number",
    "crypto-hash-method", "cycling-auto-reminders", "dali-mode",
    "darwin-init-config-from-nvram", "data-plan", "debug-board-revision", "defaults",
    "deferred-processing", "delay-sleep-for-headset-click", "device-color-policy",
    "device-colors", "device-name", "device-name-localized", "dictation", "die-id",
    "disablemigration", "disp0", "display-boot-rotation", "display-mirroring",
    "display-rotation", "displayport", "does-not-support-gamekit", "driverkit",
    "effective-production-status", "effective-production-status-ap",
    "effective-production-status-sep", "effective-security-mode",
    "effective-security-mode-ap", "effective-security-mode-sep",
    "embedded-web-browser-engine", "enc-bot-type", "enc-top-type", "encode-aac",
    "encrypted-data-partition", "enforce-googlemail", "enforce-shutter-click",
    "env-audio-exp-capable", "eos-halley-config", "ephemeral-data-mode", "esim-only",
    "euicc-chip-id", "explicitContentRestriction", "extended-workout", "external-driverkit",
    "external-hdr", "face-detection-support", "fast-switch-options",
    "fcc-logos-via-software", "fcm-type", "fillmore", "firmware-version", "flash",
    "force-supported", "form-factor", "framebuffer-identifier", "front-auto-hdr",
    "front-burst", "front-burst-image-duration", "front-cam-rotation-isp",
    "front-cam-superwide-capability", "front-depth-camera", "front-facing-camera",
    "front-flash", "front-flash-capability", "front-hdr", "front-hdr-on",
    "front-low-light-photo", "front-max-slomo-video-fps-1080p",
    "front-max-slomo-video-fps-720p", "front-max-video-fps-1080p", "front-max-video-fps-4k",
    "front-max-video-fps-720p", "front-max-video-zoom", "front-single-camera-portrait",
    "front-slowmo", "front-stage-light-portrait", "front-variable-frame-rate", "full-6",
    "function-bb_ap_time_sync", "function-button_halleffect", "function-button_ringerab",
    "function-button_ringeren", "function-button_skey", "function-button_volup", "gamekit",
    "gas-gauge-battery", "generative-model-systems", "gps", "gps-capable", "green-tea",
    "grimaldi", "gyro", "gyroscope", "h264-encoder", "h264-playback-level",
    "hall-effect-sensor", "haptics", "hardware-detents", "hardware-keyboard",
    "has-applelpm", "has-boot-chime", "has-ironman-charging", "has-sphere",
    "hd-video-capture", "hdr-image-capture", "healthkit", "hearingaid-audio-equalization",
    "hearingaid-low-energy-audio", "hearingaid-power-reduction", "hiccough-interval",
    "hide-non-default-apps", "hidpi", "high-bandwidth-radio", "hme-in-arkit",
    "home-button-type", "homescreen-wallpaper", "horseman", "housing-color",
    "hw-encode-snapshots", "hw-snapshots-need-purplegfx", "iAP2Capability",
    "iPadCapability", "iTunesFamilyID", "iap2-protocol-supported", "image4-supported",
    "international-settings", "io-surface-backed-images", "ios-perf-level-2", "ipad",
    "ipad-minimum-performance-m1", "iphone-ipad-minimum-performance-a12",
    "iphone-performance-gaming-tier", "island-notch-location", "jasper-camera",
    "kConferenceCallType", "kSimultaneousCallAndDataCurrentlySupported",
    "kSimultaneousCallAndDataSupported", "large-format-phone", "lidar-scanner",
    "live-effects", "live-photo-auto", "live-photo-capture",
    "load-thumbnails-while-scrolling", "location-reminders", "location-services",
    "long-form-audio-play", "low-power-wallet-mode", "lte-device", "luna-serial-number",
    "mac-address-bluetooth1", "mac-address-ethernet1", "mac-address-wifi1", "magnetometer",
    "main-screen-canvas-sizes", "main-screen-class", "main-screen-height",
    "main-screen-orientation", "main-screen-pitch", "main-screen-scale",
    "main-screen-width", "mandrake-supported", "marketing-name", "marketing-soc-name",
    "max-boot-time-ms", "mesa", "metal", "mic-trim-gains", "microphone",
    "mix-n-match-prevention-status", "mms", "modelIdentifier", "moment-capture",
    "multi-touch", "multitasking", "multitasking-gestures", "multitouch", "n78a-mode",
    "name", "natural-volume-arrangement", "navigation", "nfc", "nfcWithRadio", "nike-ipod",
    "nike-support", "no-coreroutine", "no-hi-res-buildings", "no-simplistic-road-mesh",
    "not-green-tea", "offline-dictation", "oled-display", "opal", "opengles-1",
    "opengles-2", "opengles-3", "opposed-power-vol-buttons", "optimize-buddy-animation",
    "ota-activation", "p3-color-space-video-recording", "panel-serial-number", "panorama",
    "partially-occluded-display", "partition-style", "pearl-calibration-data",
    "pearl-camera", "peek-ui-width", "peer-peer", "personal-hotspot", "photo-adjustments",
    "photo-capture-on-touch-down", "photo-stream", "piezo-clicker",
    "pipelined-stillimage-capability", "platinum", "portrait-lighting-strength",
    "post-effects", "power-control-features", "pressure", "product-soc-name", "prox-sensor",
    "proximity-sensor", "ptp-large-files", "public-key-accelerator",
    "raw-panel-serial-number", "rear-auto-hdr", "rear-burst", "rear-burst-image-duration",
    "rear-cam-superwide-capability", "rear-cam-telephoto-capability", "rear-facing-camera",
    "rear-focus-pixel-calibration", "rear-hdr", "rear-hdr-on", "rear-low-light-photo",
    "rear-max-slomo-video-fps-1080p", "rear-max-slomo-video-fps-720p",
    "rear-max-video-fps-1080p", "rear-max-video-fps-4k", "rear-max-video-fps-720p",
    "rear-max-video-frame_rate", "rear-max-video-zoom", "rear-slowmo",
    "rear-stage-light-portrait", "rear-variable-frame-rate", "regulatory-model-number",
    "research-enabled", "reverse-zoom", "reverse-zoom-supported", "ringer-switch", "role",
    "rosaline-serial-num", "s8000", "s8000\")", "s8001", "s8001\")", "s8003", "s8003\")",
    "sandman-support", "scandium", "screen-dimensions", "security-domain", "sensitive-ui",
    "shoebox", "sika-support", "sim", "sim-phonebook", "single-camera-portrait",
    "siri-gesture", "siri-hub", "slow-letterpress-rendering", "smc-ext-charger", "sms",
    "software-bundle-version", "software-dimming-alpha", "spatial-over-capture",
    "speaker-thiele-small", "speaker-trim-gains", "stage-light-portrait-preview",
    "stand-alone-contacts", "stereo-sound-recording", "still-camera", "stockholm",
    "studio-light-portrait-preview", "supports-3rd-party-haptics",
    "supports-absolute-altimeter", "supports-advanced-vp-chatflavor",
    "supports-always-listening", "supports-aod-vibrancy", "supports-audio-mix",
    "supports-auto-mic-mode", "supports-autodim", "supports-avatars", "supports-barge-in",
    "supports-brook", "supports-burnin-mitigation", "supports-camera-button",
    "supports-concurrent-hp-lp-mics", "supports-gcp", "supports-gray-dimming",
    "supports-grey-gestures", "supports-hypertension-pattern",
    "supports-listening-on-gesture", "supports-maps-optical-heading",
    "supports-nfc-reader-mode", "supports-on-device-siri", "supports-oyster",
    "supports-pearl-motion-detection", "supports-personal-translator",
    "supports-secure-microphone", "supports-side-btn-click-speed",
    "supports-spatial-audio-capture", "supports-third-party-drivers", "supports-twilight",
    "supports-voiceover-can-use-siri", "sw-pro-res", "syncdbv-supported", "t7000",
    "t7000\")", "t7001", "t7001\")", "target-sub-type", "telephony",
    "telephony-maximum-generation", "thin-bezel", "tnr-mode-back", "tnr-mode-front",
    "torpedo", "touch-id", "ttw-supported", "tv-out-crossfade", "tv-out-settings",
    "tvos-perf-level-1", "ui-background-quality", "ui-floating-live-app", "ui-no-parallax",
    "ui-no-procedural-wallpaper", "ui-overlay-app", "ui-pinned-app", "ui-pip",
    "ui-reachability", "ui-traffic-cheap-shaders", "ui-traffic-no-alpha",
    "ui-weather-quality", "umts-device", "unified-ipod", "unique-chip-id",
    "untrusted-remote-sysdiag", "use-syncdbv", "vaxholm", "venice", "video-camera",
    "video-cap", "video-stills", "voice-control", "voip", "volume-buttons",
    "vsh-compensation-minimum-nits", "wapi", "watch-companion", "watch-gestures",
    "watch-keyboard", "web-browser-engine", "wi-fi", "wifi", "wifi-antenna-sku-info",
    "wifi-chipset", "wifi-module-sn", "wireless-splitter", "wlan",
    "wlan.background-scan-cache", "wlan.lowlatency", "wlan.nan.enabled", "youtube",
    "youtubePlugin",
]


def obfuscate(name):
    """The exact transform libMobileGestalt applies to a property name."""
    return base64.b64encode(
        hashlib.md5(("MGCopyAnswer" + name).encode()).digest()).decode()[:22]


BY_HASH = {obfuscate(n): n for n in NAMES}


# Every obfuscated key present in libMobileGestalt.dylib on this rack's build
# (iOS 16.7.16, iPhone10,3) that the table above cannot name. Measured by reading
# the mapped image out of a live process and clamping to the module's own 452 KB
# extent: 1041 real keys, 1030 named, these 11 left.
#
# Kept because the distinction is worth reporting. A hash in here is a real Apple
# property that nobody has publicly recovered the name of. A hash in neither list
# is something else entirely, and the two deserve different words in the report.
# Brute forcing these against all 2.3 million strings in the device's shared cache
# produced nothing, so the plaintext names are not on the phone to be found.
UNRECOVERED_ON_THIS_BUILD = {
    "9f5ODNAt2gufqSI82eYnLw", "KWr9OM2iqeLQEhaHS0UshQ", "P1djMN/L3B6otgGpO9WYkw",
    "bbyFCcrPE+k6ZXIVbXSFUw", "dW6ROVcD3o5ACa4jvALJ6A", "is3zjHrEdiF6J/boqghy9A",
    "lR7sjp4tOz3cMWoEMlZrLA", "mug/QuG6jZ3CYR9p7OWQaw", "t56wS9db+T2F2bxBpYSX8Q",
    "uNNFSosc1xQM/7bwlrqLXA", "wAbB2fAjUqUc6lNBelfWMA",
}


def resolve(key):
    """Plaintext name for an obfuscated key, or None if it cannot be named.

    Anything that is not a known 22-character token returns None, so a key TikTok
    already passed in the clear falls straight through untouched.
    """
    return BY_HASH.get(key)
